=== JEE-Migration/MigrationProcessor/src/main/resources/kdmResult.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="migration">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="1" minOccurs="1" ref="microservices"/>
                <xs:element maxOccurs="1" minOccurs="1" ref="relationships"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="microservices">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="microservice"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="microservice">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" maxOccurs="unbounded" name="qualifiedType" type="xs:string"/>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string" use="required" />
        </xs:complexType>
    </xs:element>

    <xs:element name="relationships">
        <xs:complexType>
            <xs:sequence maxOccurs="unbounded" minOccurs="0">
            	<xs:choice>
            		<xs:element ref="attribute"/>
            		<xs:element ref="methodInvocation"/>
            		<xs:element ref="methodParameter"/>
            	</xs:choice>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="attribute">
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="relation">
                    <xs:sequence>
                        <xs:element  minOccurs="1" maxOccurs="unbounded" name="annotations">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="annotation" minOccurs="1" maxOccurs="1" type="xs:string"/>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>

    <xs:element name="methodInvocation">
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="relation">
                    <xs:sequence>
                        <xs:element  minOccurs="0" maxOccurs="1" name="methodSignature" type="xs:string"/>
                    </xs:sequence>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>

    <xs:element name="methodParameter">
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="relation">
                    <xs:sequence>
                        <xs:element  minOccurs="0" maxOccurs="1" name="methodSignature" type="xs:string"/>
                    </xs:sequence>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="relation">
            <xs:sequence>
                <xs:element maxOccurs="1" minOccurs="1" name="from" type="xs:string"/>
                <xs:element maxOccurs="1" minOccurs="1" name="to" type="xs:string"/>
            </xs:sequence>
    </xs:complexType>
    

</xs:schema>

=== JEE-Migration/MigrationProcessor/src/main/resources/marketplace.xml
<?xml version="1.0" encoding="UTF-8"?>
<migration
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation ="kdmResult.xsd">
    <microservices>
        <microservice name="Client Microservice">

            <!-- EJB-->
            <qualifiedType>co.edu.uniandes.csw.mpcellphone.ejbs.ClientLogic</qualifiedType>
            <qualifiedType>co.edu.uniandes.csw.mpcellphone.api.IClientLogic</qualifiedType>

            <!-- Persistence-->
            <qualifiedType>co.edu.uniandes.csw.mpcellphone.persistence.ClientPersistence</qualifiedType>
            <qualifiedType>co.edu.uniandes.csw.mpcellphone.persistence.CrudPersistence</qualifiedType>

            <!-- Entity-->
            <qualifiedType>co.edu.uniandes.csw.mpcellphone.entities.ClientEntity</qualifiedType>
            <qualifiedType>co.edu.uniandes.csw.mpcellphone.entities.CartItemEntity</qualifiedType>
            <qualifiedType>co.edu.uniandes.csw.mpcellphone.entities.ProductEntity</qualifiedType>
            <qualifiedType>co.edu.uniandes.csw.mpcellphone.entities.CellPhoneEntity</qualifiedType>
            <qualifiedType>co.edu.uniandes.csw.mpcellphone.entities.ProviderEntity</qualifiedType>
            <qualifiedType>co.edu.uniandes.csw.mpcellphone.entities.OrderEntity</qualifiedType>

            <!-- DTOS-->
            <qualifiedType>co.edu.uniandes.csw.mpcellphone.dtos.ClientDTO</qualifiedType>
            <qualifiedType>co.edu.uniandes.csw.mpcellphone.dtos.CartItemDTO</qualifiedType>
            <qualifiedType>co.edu.uniandes.csw.mpcellphone.dtos.ProductDTO</qualifiedType>
            <qualifiedType>co.edu.uniandes.csw.mpcellphone.dtos.CellPhoneDTO</qualifiedType>
            <qualifiedType>co.edu.uniandes.csw.mpcellphone.dtos.ProviderDTO</qualifiedType>
            <qualifiedType>co.edu.uniandes.csw.mpcellphone.dtos.OrderDTO</qualifiedType>
            <qualifiedType>co.edu.uniandes.csw.mpcellphone.dtos.ShipDTO</qualifiedType>
            <qualifiedType>co.edu.uniandes.csw.mpcellphone.dtos.PaymentMethodDTO</qualifiedType>
            <qualifiedType>co.edu.uniandes.csw.mpcellphone.dtos.TaxDTO</qualifiedType>

            <!-- Converter-->
            <qualifiedType>co.edu.uniandes.csw.mpcellphone.converters.ClientConverter</qualifiedType>

        </microservice>

    </microservices>
    <relationships>

    </relationships>
</migration>
